[[apps]]
name = "nvim"
src_path = "nvim"
link_mode = "soft"
dest_path_unix = "~/.config/nvim"
dest_path_win = "$APPDATA/nvim"

[[apps]]
name = "zed"
src_path = "zed"
link_mode = "soft"
dest_path_unix = "~/.config/zed"
dest_path_win = "$APPDATA/Zed"

[[apps]]
name = "wezterm"
src_path = "wezterm"
link_mode = "soft"
dest_path = "~/.config/wezterm"

[[apps]]
name = "nushell"
src_path = "nushell"
link_mode = "soft"
dest_path_unix = "~/.config/nushell"
dest_path_win = "$APPDATA/nushell"
dest_path_mac = "$HOME/Library/Application Support/nushell"

[[apps]]
name = "yazi"
src_path = "yazi"
link_mode = "soft"
dest_path_unix = "~/.config/yazi"
dest_path_win = "$APPDATA/yazi"

[[apps]]
name = "lazygit"
src_path = "lazygit"
link_mode = "soft"
dest_path_unix = "~/.config/lazygit"
dest_path_win = "$LOCALAPPDATA/lazygit"
dest_path_mac = "$HOME/Library/Application Support/lazygit"

[[apps]]
name = "starship"
src_path = "starship/starship.toml"
link_mode = "hard"
dest_path = "~/.config/starship.toml"
